# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=250)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='200', max_length=100)),
                ('final_url', models.CharField(max_length=250, null=models.URLField(max_length=250))),
                ('title', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
