# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('urlexpander', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='wayback',
            field=models.CharField(max_length=250, null=models.URLField(max_length=250)),
        ),
        migrations.AddField(
            model_name='url',
            name='wayback_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
