# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlexpander', '0003_auto_20160810_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='archive_link',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
